/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.feifan.struts.form;

/**
 * MyEclipse Struts Creation date: 07-21-2013
 * 
 * XDoclet definition:
 * 
 * @struts.form name="registerForm"
 */
public class ErrorInfo {

	private static final long serialVersionUID = 5652655120318203946L;

	private String result;

	private String usernameRsp;

	private String companyname;

	private String username;

	private String address;

	private String realname;

	private String shenfenid;

	private String sheng1;

	private String shi1;

	private String password;

	private String passwordConfirm;

	private String telephone;

	private String mobile;

	private String otherInfo;

	public String getResult() {
		return result;
	}

	public void setResult(String result) {
		this.result = result;
	}

	public String getUsernameRsp() {
		return usernameRsp;
	}

	public void setUsernameRsp(String usernameRsp) {
		this.usernameRsp = usernameRsp;
	}

	public String getCompanyname() {
		return companyname;
	}

	public void setCompanyname(String companyname) {
		this.companyname = companyname;
	}

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getRealname() {
		return realname;
	}

	public void setRealname(String realname) {
		this.realname = realname;
	}

	public String getShenfenid() {
		return shenfenid;
	}

	public void setShenfenid(String shenfenid) {
		this.shenfenid = shenfenid;
	}

	public String getSheng1() {
		return sheng1;
	}

	public void setSheng1(String sheng1) {
		this.sheng1 = sheng1;
	}

	public String getShi1() {
		return shi1;
	}

	public void setShi1(String shi1) {
		this.shi1 = shi1;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getPasswordConfirm() {
		return passwordConfirm;
	}

	public void setPasswordConfirm(String passwordConfirm) {
		this.passwordConfirm = passwordConfirm;
	}

	public String getTelephone() {
		return telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	public String getMobile() {
		return mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public String getOtherInfo() {
		return otherInfo;
	}

	public void setOtherInfo(String otherInfo) {
		this.otherInfo = otherInfo;
	}

}