/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.feifan.struts.form;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

import com.feifan.struts.bean.LeftBottomBean;
import com.feifan.struts.bean.LeftTopBean;
import com.feifan.struts.bean.RightBean;
import com.feifan.struts.bean.TopBean;

/**
 * MyEclipse Struts Creation date: 06-24-2013
 * 
 * XDoclet definition:
 * 
 * @struts.form name="registerForm"
 */
public class MainForm extends ActionForm {
	private static final long serialVersionUID = 1L;

	private TopBean topBean = new TopBean();
	private LeftBottomBean leftBottomBean = new LeftBottomBean();
	private LeftTopBean leftTopBean = new LeftTopBean();
	private RightBean rightBean = new RightBean();
	private String formEvent;
	private String openCloseFlag;
	private String conditionResultFlag;

	public TopBean getTopBean() {
		return topBean;
	}

	public void setTopBean(TopBean topBean) {
		this.topBean = topBean;
	}

	public LeftBottomBean getLeftBottomBean() {
		return leftBottomBean;
	}

	public void setLeftBottomBean(LeftBottomBean leftBottomBean) {
		this.leftBottomBean = leftBottomBean;
	}

	public LeftTopBean getLeftTopBean() {
		return leftTopBean;
	}

	public void setLeftTopBean(LeftTopBean leftTopBean) {
		this.leftTopBean = leftTopBean;
	}

	public RightBean getRightBean() {
		return rightBean;
	}

	public void setRightBean(RightBean rightBean) {
		this.rightBean = rightBean;
	}

	public String getFormEvent() {
		return formEvent;
	}

	public void setFormEvent(String formEvent) {
		this.formEvent = formEvent;
	}

	public String getOpenCloseFlag() {
		return openCloseFlag;
	}

	public void setOpenCloseFlag(String openCloseFlag) {
		this.openCloseFlag = openCloseFlag;
	}

	public String getConditionResultFlag() {
		return conditionResultFlag;
	}

	public void setConditionResultFlag(String conditionResultFlag) {
		this.conditionResultFlag = conditionResultFlag;
	}

	/**
	 * Method validate
	 * 
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/**
	 * Method reset
	 * 
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

}