/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.feifan.struts.form;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/**
 * MyEclipse Struts Creation date: 07-21-2013
 * 
 * XDoclet definition:
 * 
 * @struts.form name="registerForm"
 */
public class MoRegisterForm extends ActionForm {

	private static final long serialVersionUID = 5652655120318203946L;

	private String companyname;

	private String username;

	private String address;

	private String realname;

	private String shenfenid;

	private String sheng1;

	private String shi1;

	private String password;

	private String passwordConfirm;

	private String telephone;

	private String mobile;

	private String imgcode;

	private String formEvent;

	private String currentElement;

	private String kefuphone;

	/**
	 * Method validate
	 * 
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping, HttpServletRequest request) {
		return new ActionErrors();
	}

	/**
	 * Method reset
	 * 
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
	}

	public String getCompanyname() {
		return companyname;
	}

	public void setCompanyname(String companyname) {
		this.companyname = companyname;
	}

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getRealname() {
		return realname;
	}

	public void setRealname(String realname) {
		this.realname = realname;
	}

	public String getShenfenid() {
		return shenfenid;
	}

	public void setShenfenid(String shenfenid) {
		this.shenfenid = shenfenid;
	}

	public String getSheng1() {
		return sheng1;
	}

	public void setSheng1(String sheng1) {
		this.sheng1 = sheng1;
	}

	public String getShi1() {
		return shi1;
	}

	public void setShi1(String shi1) {
		this.shi1 = shi1;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getPasswordConfirm() {
		return passwordConfirm;
	}

	public void setPasswordConfirm(String passwordConfirm) {
		this.passwordConfirm = passwordConfirm;
	}

	public String getTelephone() {
		return telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	public String getMobile() {
		return mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public String getImgcode() {
		return imgcode;
	}

	public void setImgcode(String imgcode) {
		this.imgcode = imgcode;
	}

	public String getFormEvent() {
		return formEvent;
	}

	public void setFormEvent(String formEvent) {
		this.formEvent = formEvent;
	}

	public String getCurrentElement() {
		return currentElement;
	}

	public void setCurrentElement(String currentElement) {
		this.currentElement = currentElement;
	}

	public String getKefuphone() {
		return kefuphone;
	}

	public void setKefuphone(String kefuphone) {
		this.kefuphone = kefuphone;
	}

}