/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.feifan.struts.form;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;

import com.feifan.struts.common.CommonUtility;

/**
 * MyEclipse Struts Creation date: 07-21-2013
 * 
 * XDoclet definition:
 * 
 * @struts.form name="registerForm"
 */
public class RegisterForm extends ActionForm {

	private static final long serialVersionUID = 5652655120318203946L;

	private String companyname;

	private String username;

	private String address;

	private String realname;

	private String shenfenid;

	private String sheng1;

	private String shi1;

	private String password;

	private String passwordConfirm;

	private String telephone;

	private String mobile;

	private String imgcode;

	private String formEvent;

	private String kefuphone;

	/**
	 * Method validate
	 * 
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping, HttpServletRequest request) {

		ActionErrors actionErrors = new ActionErrors();
		if ("REGISTER".equals(formEvent)) {
			// 如果session失效，自动清空
			if (request.getSession().getAttribute("shengSession") == null) {
				reset(mapping, request);
			}

			// 单位名称
			if (companyname.trim().equals("")) {
				actionErrors.add("companyname", new ActionMessage("LOGISTICS_001", "单位名称"));
			} else if (!CommonUtility.isLengthOK(companyname, 2, 12)) {
				actionErrors.add("companyname", new ActionMessage("LOGISTICS_007", "单位名称", 2, 12));
			} else if (!CommonUtility.isChineseChar(companyname)) {
				actionErrors.add("companyname", new ActionMessage("LOGISTICS_005", "单位名称"));
			}
			// 用户名
			if (username.trim().equals("")) {
				actionErrors.add("username", new ActionMessage("LOGISTICS_001", "用户名"));
			} else if (!CommonUtility.isLengthOK(username, 2, 8)) {
				actionErrors.add("username", new ActionMessage("LOGISTICS_007", "用户名", 2, 8));
			} else if (!CommonUtility.isUsername(username)) {
				actionErrors.add("username", new ActionMessage("LOGISTICS_006", "用户名"));
			}
			// 密码，密码确认
			if (password.trim().equals("")) {
				actionErrors.add("password", new ActionMessage("LOGISTICS_001", "密码"));
			} else if (!CommonUtility.isLengthOK(password, 6, 8)) {
				actionErrors.add("password", new ActionMessage("LOGISTICS_007", "密码", 6, 8));
			} else if (!password.equals(passwordConfirm)) {
				actionErrors.add("passwordConfirm", new ActionMessage("LOGISTICS_003"));
			}
			// 真实姓名
			if (realname.trim().equals("")) {
				actionErrors.add("realname", new ActionMessage("LOGISTICS_001", "真实姓名"));
			} else if (!CommonUtility.isLengthOK(realname, 2, 4)) {
				actionErrors.add("realname", new ActionMessage("LOGISTICS_007", "真实姓名", 2, 4));
			} else if (!CommonUtility.isChineseChar(realname)) {
				actionErrors.add("realname", new ActionMessage("LOGISTICS_005", "真实姓名"));
			}
			// 身份证号
			if (shenfenid.trim().equals("")) {
				actionErrors.add("shenfenid", new ActionMessage("LOGISTICS_001", "身份证号"));
			} else if (!CommonUtility.isLengthOK(shenfenid, 18, 18)) {
				actionErrors.add("shenfenid", new ActionMessage("LOGISTICS_008", "身份证号", 18));
			} else if (!CommonUtility.isPerson_Num(shenfenid)) {
				actionErrors.add("shenfenid", new ActionMessage("LOGISTICS_002", "身份证号"));
			}
			// 省
			if (sheng1.trim().equals("")) {
				actionErrors.add("sheng1", new ActionMessage("LOGISTICS_001", "省"));
			}
			// 市
			if (shi1.trim().equals("")) {
				actionErrors.add("shi1", new ActionMessage("LOGISTICS_001", "市"));
			}
			// 地址信息
			if (address.trim().equals("")) {
				actionErrors.add("address", new ActionMessage("LOGISTICS_001", "地址信息"));
			}
			// 手机
			if (mobile.trim().equals("")) {
				actionErrors.add("mobile", new ActionMessage("LOGISTICS_001", "手机"));
			} else if (!CommonUtility.isLengthOK(mobile, 11, 11)) {
				actionErrors.add("mobile", new ActionMessage("LOGISTICS_008", "手机", 11));
			} else if (!CommonUtility.isMobile(mobile)) {
				actionErrors.add("mobile", new ActionMessage("LOGISTICS_002", "手机"));
			}
			// 固定电话
			if (telephone.trim().equals("")) {
				actionErrors.add("telephone", new ActionMessage("LOGISTICS_001", "固定电话"));
			} else if (!CommonUtility.isLengthOK(telephone, 11, 12)) {
				actionErrors.add("telephone", new ActionMessage("LOGISTICS_007", "固定电话", 11, 12));
			} else if (!CommonUtility.isTelephone(telephone)) {
				actionErrors.add("telephone", new ActionMessage("LOGISTICS_002", "固定电话"));
			}
			// 验证码
			if (imgcode.trim().equals("")) {
				actionErrors.add("imgcode", new ActionMessage("LOGISTICS_001", "验证码"));
			} else if (!((String) request.getSession().getAttribute("randomCode")).equalsIgnoreCase(imgcode)) {
				actionErrors.add("imgcode", new ActionMessage("LOGISTICS_009", "验证码"));
			}

		}

		return actionErrors;

	}

	/**
	 * Method reset
	 * 
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		companyname = "";

		username = "";

		address = "";

		realname = "";

		shenfenid = "";

		sheng1 = "";

		shi1 = "";

		password = "";

		passwordConfirm = "";

		telephone = "";

		mobile = "";

		imgcode = "";

	}

	public String getCompanyname() {
		return companyname;
	}

	public void setCompanyname(String companyname) {
		this.companyname = companyname;
	}

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getRealname() {
		return realname;
	}

	public void setRealname(String realname) {
		this.realname = realname;
	}

	public String getShenfenid() {
		return shenfenid;
	}

	public void setShenfenid(String shenfenid) {
		this.shenfenid = shenfenid;
	}

	public String getSheng1() {
		return sheng1;
	}

	public void setSheng1(String sheng1) {
		this.sheng1 = sheng1;
	}

	public String getShi1() {
		return shi1;
	}

	public void setShi1(String shi1) {
		this.shi1 = shi1;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getPasswordConfirm() {
		return passwordConfirm;
	}

	public void setPasswordConfirm(String passwordConfirm) {
		this.passwordConfirm = passwordConfirm;
	}

	public String getTelephone() {
		return telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	public String getMobile() {
		return mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public String getImgcode() {
		return imgcode;
	}

	public void setImgcode(String imgcode) {
		this.imgcode = imgcode;
	}

	public String getFormEvent() {
		return formEvent;
	}

	public void setFormEvent(String formEvent) {
		this.formEvent = formEvent;
	}

	public String getKefuphone() {
		return kefuphone;
	}

	public void setKefuphone(String kefuphone) {
		this.kefuphone = kefuphone;
	}

}